### ISSUE TITLE
Bitcode and build upload error

### ISSUE THREAD

**Issue by PCGurjar** [microsoft/MapsSDK-Native#17]
While using Bing Map iOS SDK version0.2.0 in our project and Bitcode is enabled then, Product doesn't Archive, so we are unable to make a build.

When we disable the Bitcode at this time Product is Archived successfully, but while upload this on Appstore we are getting unexpected "CFBundleExecutableKey" error.
Please provide a solution for this.
![image001](https://user-images.githubusercontent.com/20769473/65486661-a7198500-dec2-11e9-9b0d-62fa7b18456f.png)
![image002](https://user-images.githubusercontent.com/20769473/65486676-b00a5680-dec2-11e9-8198-5fe9cadc0c33.png)

**Comment by JuanPapas** [comment]
Thank you for reporting this.
The fix for both issues will be available in our next v1 release very soon.  Specifically, we had to fix our build configuration settings to address the bitcode problem in our framework.  Also we had to fix an issue with one of our Info.plist files, where the MicrosoftMapsBundle which is a resource was incorrectly tagged as executable.

**Comment by PCGurjar** [comment]
Thanks, for your reply,
When we expect your stable build, actually we are in phase to release our product.

**Comment by JuanPapas** [comment]
We just published version 1.0.0, where this issue is fixed.
